version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - '.env'
    command: bash -c "rails s -b 0.0.0.0"
    depends_on:
      - db

  db:
    image: postgres:alpine3.19
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - "5432:5432"